# _____                                  _____
# |  __ \                                / ____|                              _
# | |  | | _ __  ___   __ _  _ __ ___   | (___    ___  _ __ __   __ ___  _ __(_)
# | |  | || '__|/ _ \ / _` || '_ ` _ \   \___ \  / _ \| '__|\ \ / // _ \| '__|
# | |__| || |  |  __/| (_| || | | | | |  ____) ||  __/| |    \ V /|  __/| |   _
# |_____/ |_|   \___| \__,_||_| |_| |_| |_____/  \___||_|     \_/  \___||_|  (_)
#           ______     _       _           ____   _         _
#          |  ____|   (_)     | |         |  _ \ | |       | |
#  ______  | |__  ___  _  ___ | |_  _   _ | |_) || |  ___  | | __ ___
# |______| |  __|/ _ \| |/ __|| __|| | | ||  _ < | | / _ \ | |/ // _ \
#          | |  |  __/| |\__ \| |_ | |_| || |_) || || (_) ||   <|  __/
#          |_|   \___||_||___/ \__| \__, ||____/ |_| \___/ |_|\_\\___|
#                                    __/ |
#                                   |___/

settings:
  # 冲击的力度
  charge-power: 2.1
  # 可设置每次冲击后减少的饥饿度以防止频繁冲刺
  food-level-reduce: 0
  # 发动冲击时所需要拿在手上的物品,不建议设置为0
  feisty-item: "3:0"
  # 是否在空中关闭移动监测
  keep-movement-check: on
  # 连续冲刺冷却,单位ms
  cooldown: 1000